version: '3.8'
services:
    node-app:
        build: .
        image: node-app
        environment:
            - 'MONGODB_URL=mongodb://mongodb:27017/node-boilerplate'
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
        volumes:
            - '.:/src'
        networks:
            - node-network
    mongodb:
        image: 'mongo:6-jammy'
        ports:
            - '27017:27017'
        volumes:
            - 'dbdata6:/data/db'
        networks:
            - node-network
volumes:
    dbdata6: null
networks:
    node-network:
        driver: bridge
        ipam:
            driver: 'default'
            config:
                - subnet: '172.24.0.2/24'
